version: '3.3'
services:
  elasticsearch:
    image: 'elasticsearch:8.8.1'
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
      - 'bootstrap.memory_lock=true'
      - 'ES_JAVA_OPTS=-Xms2g -Xmx2g'
    ports:
      - '9200:9200'
      - '9300:9300'
